name: Run checks and deploy to GCP
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
jobs:
  Run-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: npm run build
      - name: Build for production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run build:prod
      - name: Deploy application
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
